# Generated by Django 6.0.2 on 2026-04-03 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenreStreamStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('stream_count', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'ordering': ['-stream_count'],
            },
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streamed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-streamed_at'],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_streams', models.PositiveBigIntegerField(db_index=True, default=0)),
                ('last_streamed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-total_streams'],
            },
        ),
    ]
