# Generated by Django 6.0.2 on 2026-03-24 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streamed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='music.song')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='streams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-streamed_at'],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_streams', models.PositiveBigIntegerField(db_index=True, default=0)),
                ('last_streamed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-total_streams'],
            },
        ),
        migrations.CreateModel(
            name='GenreStreamStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('stream_count', models.PositiveBigIntegerField(default=0)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_stats', to='music.genre')),
            ],
            options={
                'ordering': ['-stream_count'],
                'unique_together': {('genre', 'date')},
            },
        ),
    ]
